In [4]:
%matplotlib inline
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

In [48]:
# Read the csv file into a pandas DataFrame
df = pd.read_excel('../Resources/PopulationEstimates.xls',skiprows=2)
# df = df.iloc[1:]
# Drop the null columns where all values are null
df = df.dropna(axis='columns', how='all')
# Drop the null rows
df = df.dropna()
df.head()

,FIPS,State,Area_Name,Rural-urban_Continuum Code_2003,Rural-urban_Continuum Code_2013,Urban_Influence_Code_2003,Urban_Influence_Code_2013,Economic_typology_2015,CENSUS_2010_POP,ESTIMATES_BASE_2010,...,R_DOMESTIC_MIG_2017,R_DOMESTIC_MIG_2018,R_NET_MIG_2011,R_NET_MIG_2012,R_NET_MIG_2013,R_NET_MIG_2014,R_NET_MIG_2015,R_NET_MIG_2016,R_NET_MIG_2017,R_NET_MIG_2018
2,1001,AL,Autauga County,2.0,2.0,2.0,2.0,0.0,54571,54574,...,1.066088,0.666403,6.002073,-6.119262,-3.885124,1.971001,-1.859380,5.250727,1.029950,0.630381
3,1003,AL,Baldwin County,4.0,3.0,5.0,2.0,5.0,182265,182264,...,21.996950,24.298662,16.345147,17.638173,22.876199,20.239802,17.932091,21.484903,22.534622,24.846682
4,1005,AL,Barbour County,6.0,6.0,6.0,6.0,3.0,27457,27457,...,-25.501697,-9.072923,0.256035,-6.786002,-8.093425,-5.102231,-15.531931,-18.152860,-25.030896,-8.593297
5,1007,AL,Bibb County,1.0,1.0,1.0,1.0,0.0,22915,22920,...,-3.589550,-7.029251,-5.041759,-3.787629,-5.666224,1.065317,1.507660,-0.753246,-3.146396,-6.584362
6,1009,AL,Blount County,1.0,1.0,1.0,1.0,0.0,57322,57321,...,6.224858,-0.172910,0.243633,-1.633022,-0.295188,-1.980336,-1.286475,-1.025739,6.363573,-0.034582

In [51]:
for col in df.columns: 
    print(col)

FIPS
State
Area_Name
Rural-urban_Continuum Code_2003
Rural-urban_Continuum Code_2013
Urban_Influence_Code_2003
Urban_Influence_Code_2013
Economic_typology_2015
CENSUS_2010_POP
ESTIMATES_BASE_2010
POP_ESTIMATE_2010
POP_ESTIMATE_2011
POP_ESTIMATE_2012
POP_ESTIMATE_2013
POP_ESTIMATE_2014
POP_ESTIMATE_2015
POP_ESTIMATE_2016
POP_ESTIMATE_2017
POP_ESTIMATE_2018
N_POP_CHG_2010
N_POP_CHG_2011
N_POP_CHG_2012
N_POP_CHG_2013
N_POP_CHG_2014
N_POP_CHG_2015
N_POP_CHG_2016
N_POP_CHG_2017
N_POP_CHG_2018
Births_2010
Births_2011
Births_2012
Births_2013
Births_2014
Births_2015
Births_2016
Births_2017
Births_2018
Deaths_2010
Deaths_2011
Deaths_2012
Deaths_2013
Deaths_2014
Deaths_2015
Deaths_2016
Deaths_2017
Deaths_2018
NATURAL_INC_2010
NATURAL_INC_2011
NATURAL_INC_2012
NATURAL_INC_2013
NATURAL_INC_2014
NATURAL_INC_2015
NATURAL_INC_2016
NATURAL_INC_2017
NATURAL_INC_2018
INTERNATIONAL_MIG_2010
INTERNATIONAL_MIG_2011
INTERNATIONAL_MIG_2012
INTERNATIONAL_MIG_2013
INTERNATIONAL_MIG_2014
INTERNATIONAL_MIG_2015
INTERNATIONAL_MIG_2016
INTERNATIONAL_MIG_2017
INTERNATIONAL_MIG_2018
DOMESTIC_MIG_2010
DOMESTIC_MIG_2011
DOMESTIC_MIG_2012
DOMESTIC_MIG_2013
DOMESTIC_MIG_2014
DOMESTIC_MIG_2015
DOMESTIC_MIG_2016
DOMESTIC_MIG_2017
DOMESTIC_MIG_2018
NET_MIG_2010
NET_MIG_2011
NET_MIG_2012
NET_MIG_2013
NET_MIG_2014
NET_MIG_2015
NET_MIG_2016
NET_MIG_2017
NET_MIG_2018
RESIDUAL_2010
RESIDUAL_2011
RESIDUAL_2012
RESIDUAL_2013
RESIDUAL_2014
RESIDUAL_2015
RESIDUAL_2016
RESIDUAL_2017
RESIDUAL_2018
GQ_ESTIMATES_BASE_2010
GQ_ESTIMATES_2010
GQ_ESTIMATES_2011
GQ_ESTIMATES_2012
GQ_ESTIMATES_2013
GQ_ESTIMATES_2014
GQ_ESTIMATES_2015
GQ_ESTIMATES_2016
GQ_ESTIMATES_2017
GQ_ESTIMATES_2018
R_birth_2011
R_birth_2012
R_birth_2013
R_birth_2014
R_birth_2015
R_birth_2016
R_birth_2017
R_birth_2018
R_death_2011
R_death_2012
R_death_2013
R_death_2014
R_death_2015
R_death_2016
R_death_2017
R_death_2018
R_NATURAL_INC_2011
R_NATURAL_INC_2012
R_NATURAL_INC_2013
R_NATURAL_INC_2014
R_NATURAL_INC_2015
R_NATURAL_INC_2016
R_NATURAL_INC_2017
R_NATURAL_INC_2018
R_INTERNATIONAL_MIG_2011
R_INTERNATIONAL_MIG_2012
R_INTERNATIONAL_MIG_2013
R_INTERNATIONAL_MIG_2014
R_INTERNATIONAL_MIG_2015
R_INTERNATIONAL_MIG_2016
R_INTERNATIONAL_MIG_2017
R_INTERNATIONAL_MIG_2018
R_DOMESTIC_MIG_2011
R_DOMESTIC_MIG_2012
R_DOMESTIC_MIG_2013
R_DOMESTIC_MIG_2014
R_DOMESTIC_MIG_2015
R_DOMESTIC_MIG_2016
R_DOMESTIC_MIG_2017
R_DOMESTIC_MIG_2018
R_NET_MIG_2011
R_NET_MIG_2012
R_NET_MIG_2013
R_NET_MIG_2014
R_NET_MIG_2015
R_NET_MIG_2016
R_NET_MIG_2017
R_NET_MIG_2018

In [49]:
# Read the csv file into a pandas DataFrame
df1 = pd.read_excel('../Resources/Unemployment.xls',skiprows=7)
# df = df.iloc[1:]
# Drop the null columns where all values are null
df1 = df1.dropna(axis='columns', how='all')
# Drop the null rows
df1 = df1.dropna()
df1.head()

,FIPS,State,Area_name,Rural_urban_continuum_code_2013,Urban_influence_code_2013,Metro_2013,Civilian_labor_force_2007,Employed_2007,Unemployed_2007,Unemployment_rate_2007,...,Civilian_labor_force_2017,Employed_2017,Unemployed_2017,Unemployment_rate_2017,Civilian_labor_force_2018,Employed_2018,Unemployed_2018,Unemployment_rate_2018,Median_Household_Income_2017,Med_HH_Income_Percent_of_State_Total_2017
2,1001,AL,"Autauga County, AL",2.0,2.0,1.0,24383.0,23577.0,806.0,3.3,...,25972.0,24958.0,1014.0,3.9,25957.0,25015.0,942.0,3.6,58343.0,121.1
3,1003,AL,"Baldwin County, AL",3.0,2.0,1.0,82659.0,80099.0,2560.0,3.1,...,92090.0,88342.0,3748.0,4.1,93849.0,90456.0,3393.0,3.6,56607.0,117.5
4,1005,AL,"Barbour County, AL",6.0,6.0,0.0,10334.0,9684.0,650.0,6.3,...,8317.0,7831.0,486.0,5.8,8373.0,7940.0,433.0,5.2,32490.0,67.4
5,1007,AL,"Bibb County, AL",1.0,1.0,1.0,8791.0,8432.0,359.0,4.1,...,8550.0,8174.0,376.0,4.4,8661.0,8317.0,344.0,4.0,45795.0,95.0
6,1009,AL,"Blount County, AL",1.0,1.0,1.0,26629.0,25780.0,849.0,3.2,...,24725.0,23726.0,999.0,4.0,25006.0,24128.0,878.0,3.5,48253.0,100.1

In [53]:
# list(df1.columns)
for col in df1.columns: 
    print(col)

FIPS
State
Area_name
Rural_urban_continuum_code_2013
Urban_influence_code_2013
Metro_2013
Civilian_labor_force_2007
Employed_2007
Unemployed_2007
Unemployment_rate_2007
Civilian_labor_force_2008
Employed_2008
Unemployed_2008
Unemployment_rate_2008
Civilian_labor_force_2009
Employed_2009
Unemployed_2009
Unemployment_rate_2009
Civilian_labor_force_2010
Employed_2010
Unemployed_2010
Unemployment_rate_2010
Civilian_labor_force_2011
Employed_2011
Unemployed_2011
Unemployment_rate_2011
Civilian_labor_force_2012
Employed_2012
Unemployed_2012
Unemployment_rate_2012
Civilian_labor_force_2013
Employed_2013
Unemployed_2013
Unemployment_rate_2013
Civilian_labor_force_2014
Employed_2014
Unemployed_2014
Unemployment_rate_2014
Civilian_labor_force_2015
Employed_2015
Unemployed_2015
Unemployment_rate_2015
Civilian_labor_force_2016
Employed_2016
Unemployed_2016
Unemployment_rate_2016
Civilian_labor_force_2017
Employed_2017
Unemployed_2017
Unemployment_rate_2017
Civilian_labor_force_2018
Employed_2018
Unemployed_2018
Unemployment_rate_2018
Median_Household_Income_2017
Med_HH_Income_Percent_of_State_Total_2017